### ISSUE TITLE
Linux AppImage Connection "default" was not found

### ISSUE THREAD

**Issue by richard-ecomus** [nervosnetwork/neuron#2380]
When I execute the AppImage on Linux Mint 19.1, the GUI appears with the error message 'Connection "default" was not found'. Running from the CLI I get this error: 

`16:54:49.152 › SQLite package has not been found installed. Try to install it: npm install sqlite3 --save`

When I try to generate the debug .zip file, I get the same error in a dialog box. Here is the trace echoed on the CLI when running the app:

```
16:54:51.542 › API Controller:	channel handling error: ConnectionNotFoundError: Connection "default" was not found. ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/error/ConnectionNotFoundError.js:10:28)
    at ConnectionManager.get (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:38:19)
    at Object.getConnection (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/index.js:245:35)
    at Function.getAddressesByWalletId (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/services/addresses.js:181:48)
    at Function.getAddressesWithBalancesByWalletId (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/services/addresses.js:203:38)
    at WalletsController.getAllAddresses (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/wallets.js:289:54)
    at /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:120:72
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:451:33
    at async node:electron/js2c/browser_init:197:563
16:54:51.790 › API Controller:	channel handling error: ConnectionNotFoundError: Connection "default" was not found. ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/error/ConnectionNotFoundError.js:10:28)
    at ConnectionManager.get (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:38:19)
    at Object.getConnection (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/index.js:245:35)
    at Function.getAddressesByWalletId (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/services/addresses.js:181:48)
    at TransactionsController.getAll (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/transactions.js:21:54)
    at /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:240:78
    at /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:451:39
    at node:electron/js2c/browser_init:197:579
    at Object.<anonymous> (node:electron/js2c/browser_init:161:10272)
    at Object.emit (node:events:394:28)
16:54:51.909 › API Controller:	channel handling error: ConnectionNotFoundError: Connection "default" was not found. ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/error/ConnectionNotFoundError.js:10:28)
    at ConnectionManager.get (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/connection/ConnectionManager.js:38:19)
    at Object.getConnection (/tmp/.mount_NeuronosAQOQ/resources/app.asar/node_modules/typeorm/index.js:245:35)
    at Function.getAddressesByWalletId (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/services/addresses.js:181:48)
    at TransactionsController.getAll (/tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/transactions.js:21:54)
    at /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:240:78
    at /tmp/.mount_NeuronosAQOQ/resources/app.asar/dist/controllers/api.js:451:39
    at node:electron/js2c/browser_init:197:579
    at Object.<anonymous> (node:electron/js2c/browser_init:161:10272)
    at Object.emit (node:events:394:28)
```

**Comment by Keith-CY** [comment]
Hi @richard-ecomus 

We will set a test environment of Mint 19.1 to debug this problem.

This error occurred before due to sqlite3 file being broken, I'm not sure if it is the same case because we don't have many info, but I think you may have a try to remove the cache manually and restart Neuron to see if it works, Neuron@v0.103.0 uses a feature of CKB node to boost synchronization so it won't take long as before.

The cache of mainnet is located at `~/.config/Neuron/cells/cell-0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5.sqlite`, you can simply rename it then Neuron will generate a new one.

**Comment by richard-ecomus** [comment]
Hi @Keith-CY,

Thank you for your reply. I tried moving the cache file to one side, but the problem remains as before. Please let me know if I can provide any other info to help debug this.

**Comment by Keith-CY** [comment]
Hi @richard-ecomus 

Sorry for replying so late.

We were trying to set the test environment on AWS and Aliyun but there isn't a distribute of Mint 19.1.

So I launched Mint 19.1 and Mint 20.3 in Virtual Box and found a similar error in Mint 19.1

If you can see `libva error: va_getDriverName() failed with unknown libva error driver_name=(null)` in the terminal, it should be the same one, and I'll try to fix it within the VM.

**Comment by Keith-CY** [comment]
> Hi @richard-ecomus
> 
> Sorry for replying so late.
> 
> We were trying to set the test environment on AWS and Aliyun but there isn't a distribute of Mint 19.1.
> 
> So I launched Mint 19.1 and Mint 20.3 in Virtual Box and found a similar error in Mint 19.1
> 
> If you can see `libva error: va_getDriverName() failed with unknown libva error driver_name=(null)` in the terminal, it should be the same one, and I'll try to fix it within the VM.

Correct me, they are two separate errors, but I'll try to fix them in the VM first.

**Comment by richard-ecomus** [comment]
Hi @Keith-CY,

Have checked the output in the console and can't see anything related to libva I'm afraid. The only errors I get are related to the missing SQLite package npm package.

Cheers

**Comment by eyeberic** [comment]
I am facing the same error as well. 

* Version: Neuron-v0.103.0-x86_64.AppImage 

I cannot export debug log because the output is malformed when trying to open up. 

> The cache of mainnet is located at ~/.config/Neuron/cells/cell-0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5.sqlite

I also did not find the cache at the `~/.config/Neuron/` directory.

**Comment by eyeberic** [comment]
Hi @Keith-CY . 
Just want to follow-up on this issue as I'm not able to perform any transaction with the Neuron Wallet being in this broken state. 
Let me know if you need further logging details.

**Comment by Keith-CY** [comment]
> Hi @Keith-CY . Just want to follow-up on this issue as I'm not able to perform any transaction with the Neuron Wallet being in this broken state. Let me know if you need further logging details.

Hi @eyeberic 

Sorry for replying late since I'm still working on this issue.

The error is introduced by upgrading `sqlite3` from v5.0.2 to v5.0.3. I'm still trying to find out a solution with v5.0.3.

Neuron will be released this week and `sqlite3` will be degraded to v5.0.2 if necessary.

**Comment by Keith-CY** [comment]
> Hi @Keith-CY . Just want to follow-up on this issue as I'm not able to perform any transaction with the Neuron Wallet being in this broken state. Let me know if you need further logging details.

And I've a workaround confirmed.

Neuron@v0.101.3 works on mint 19.1 but it has an un-hardforked ckb node inside, we can run a ckb node manually (https://docs.nervos.org/docs/basics/guides/mainnet/) to replace the inside one.

**Comment by Keith-CY** [comment]
Fixed by PR https://github.com/nervosnetwork/neuron/pull/2417

**Comment by Keith-CY** [comment]
Hi @richard-ecomus @eyeberic 
Neuron v0.103.1 (https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1) was just released and works in mint 19.1 and mint 20.3

**Comment by richard-ecomus** [comment]
Hi @Keith-CY, all working for me now, thank you very much. Guess this can be closed if it's workign for @eyeberic too.

**Comment by eyeberic** [comment]
Confirmed to be resolved in Neuron v0.103.1 (https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1). 

Thanks for your hard work into this, and feel free to close this out.
