### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by AlexanderFSP** [nervosnetwork/neuron#2527]
**Describe the bug**
After successfully synchronizing the wallet with the nervos blockchain, the application throws an error (at a completely random time). When you try to close this prompt - **it appears again and again** (doing so it prevents to close the wallet, I was able to do it only using the system monitor).

Neuron Version: 0.103.2
CKB Client Version: v0.103.0
OS: Ubuntu 22.04.1 LTS 64-bit

**Debug info**

```
[2022-11-14 06:25:07.145] [info] Database:	saved synced block #8475945
[2022-11-14 06:27:07.626] [info] Database:	saved synced block #8475955
[2022-11-14 10:04:50.543] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2022-11-14 10:04:50.647] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2022-11-14 10:04:50.754] [error] Network:	fail to connect to the network. Is CKB node running?
[2022-11-14 10:04:50.918] [info] Network:	switched to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://localhost:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2022-11-14 10:04:51.113] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2022-11-14 10:04:51.216] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2022-11-14 10:04:51.316] [info] CKB:	external RPC on default uri not detected, starting bundled CKB node.
[2022-11-14 10:04:51.317] [info] CKB:	Initializing node...
[2022-11-14 10:04:51.318] [info] CKB:	init: config file detected, skip ckb init.
[2022-11-14 10:04:51.318] [info] CKB:	starting node...
[2022-11-14 10:04:57.598] [info] Network:	reconnected to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://localhost:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2022-11-14 10:05:00.618] [info] Indexer:	start: PORT: 8118...
[2022-11-14 10:05:00.620] [warn] function call error: Error: Port is not reachable, retry 2 ...
[2022-11-14 10:05:01.620] [info] Sync:	start
[2022-11-14 10:05:02.635] [info] Queue:	start
[2022-11-14 10:05:02.695] [info] Database:	saved synced block #8477198
[2022-11-14 10:06:12.952] [info] Database:	saved synced block #8477208
[2022-11-14 10:08:28.467] [info] Database:	saved synced block #8477218
[2022-11-14 10:11:39.087] [info] Database:	saved synced block #8477229
[2022-11-14 10:13:14.464] [info] Database:	saved synced block #8477239
[2022-11-14 10:15:04.851] [info] Database:	saved synced block #8477249
[2022-11-14 10:17:10.255] [info] Database:	saved synced block #8477259
[2022-11-14 10:19:01.021] [info] Database:	saved synced block #8477269
[2022-11-14 10:21:42.120] [info] Database:	saved synced block #8477279
[2022-11-14 10:24:12.909] [info] Database:	saved synced block #8477289
[2022-11-14 10:25:48.383] [info] Database:	saved synced block #8477302
[2022-11-14 10:27:53.966] [info] Database:	saved synced block #8477312
[2022-11-14 10:28:59.288] [info] Database:	saved synced block #8477322
[2022-11-14 10:30:44.734] [info] Database:	saved synced block #8477333
[2022-11-14 10:32:55.458] [info] Database:	saved synced block #8477343
[2022-11-14 10:33:03.491] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '/dev/hidraw1',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2022-11-14 10:33:03.552] [warn] API Controller:	channel handling error: Error: cannot open device with path /dev/hidraw1 Error: cannot open device with path /dev/hidraw1
    at HardwareController.connectDevice (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/hardware.js:17:19)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:440:17
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:33:30.743] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '/dev/hidraw1',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2022-11-14 10:33:30.744] [warn] API Controller:	channel handling error: Error: cannot open device with path /dev/hidraw1 Error: cannot open device with path /dev/hidraw1
    at HardwareController.connectDevice (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/hardware.js:17:19)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:440:17
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:33:38.377] [info] Find devices:	 [
  [
    {
      isBluetooth: false,
      descriptor: '/dev/hidraw3',
      vendorId: 11415,
      manufacturer: 'Ledger',
      product: 'Nano X',
      addressIndex: 0,
      addressType: 0
    }
  ]
]
[2022-11-14 10:33:38.387] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '/dev/hidraw3',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2022-11-14 10:33:39.699] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '/dev/hidraw3',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2022-11-14 10:34:04.282] [warn] API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at Function.TransactionGenerator.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/tx/transaction-generator.js:946:15)
    at async TransactionSender.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/transaction-sender.js:182:24)
    at async DaoController.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/dao.js:37:20)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:34:16.891] [warn] API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at Function.TransactionGenerator.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/tx/transaction-generator.js:946:15)
    at async TransactionSender.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/transaction-sender.js:182:24)
    at async DaoController.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/dao.js:37:20)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:34:22.024] [warn] API Controller:	channel handling error: Error: Insufficient available balance, please try again when last transaction has been confirmed. Error: Insufficient available balance, please try again when last transaction has been confirmed.
    at Function.CellsService.gatherInputs (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/cells.js:853:19)
    at async Function.generateCreateAnyoneCanPayTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/tx/transaction-generator.js:111:67)
    at async Function.generateCreateTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/asset-account-service.js:167:18)
    at async AssetAccountController.generateCreateTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/asset-account.js:89:24)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:34:23.714] [warn] API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at Function.TransactionGenerator.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/tx/transaction-generator.js:946:15)
    at async TransactionSender.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/services/transaction-sender.js:182:24)
    at async DaoController.generateDepositAllTx (/tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/dao.js:37:20)
    at async /tmp/.mount_NeuronNfH4J0/resources/app.asar/dist/controllers/api.js:509:33
    at async node:electron/js2c/browser_init:197:563
[2022-11-14 10:34:51.072] [info] Database:	saved synced block #8477354
[2022-11-14 10:36:21.665] [info] Database:	saved synced block #8477364
[2022-11-14 10:38:27.391] [info] Database:	saved synced block #8477374
[2022-11-14 10:40:27.926] [info] Database:	saved synced block #8477385
[2022-11-14 10:42:03.452] [info] Database:	saved synced block #8477396
[2022-11-14 10:44:39.109] [info] Database:	saved synced block #8477406
[2022-11-14 10:46:34.603] [info] Database:	saved synced block #8477416
[2022-11-14 10:48:04.997] [info] Database:	saved synced block #8477426
[2022-11-14 10:49:55.410] [info] Database:	saved synced block #8477436
[2022-11-14 10:52:06.029] [info] Database:	saved synced block #8477448
[2022-11-14 10:53:31.417] [info] Database:	saved synced block #8477458
[2022-11-14 11:20:37.920] [info] Network:	switched to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://localhost:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2022-11-14 11:20:40.946] [info] Indexer:	start: PORT: 8119...
[2022-11-14 11:20:40.948] [warn] function call error: Error: Port is not reachable, retry 2 ...
[2022-11-14 11:20:41.959] [warn] function call error: Error: Port is not reachable, retry 3 ...
[2022-11-14 11:20:42.963] [warn] function call error: Error: Port is not reachable, retry 4 ...
[2022-11-14 11:20:43.966] [warn] function call error: Error: Port is not reachable, retry 5 ...
```

**Screenshots**

![Screenshot from 2022-11-14 11-18-08](https://user-images.githubusercontent.com/30397060/201567959-9ec08305-5541-4be1-a156-abfdee0716b0.png)

**Comment by yanguoyu** [comment]
@AlexanderFSP Is it convenient for you to upload the full log?

**Comment by AlexanderFSP** [comment]
@yanguoyu , sure, here it is: [main.log](https://github.com/nervosnetwork/neuron/files/9999295/main.log)
