### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by Arkaier** [nervosnetwork/neuron#2746]
### Detail of the issue

neuron Wallet not synchronizing

### bundled-ckb.log

```shell
File not found
```

### main.log

```shell
[2023-06-15 15:33:47.640] [info]  App:	Neuron is starting
[2023-06-15 15:33:48.015] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:33:48.140] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:33:48.249] [error] Network:	fail to connect to the network. Is CKB node running?
[2023-06-15 15:33:51.077] [info]  Network:	switched to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2023-06-15 15:33:52.106] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:33:52.221] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:33:52.327] [info]  CKB:	external RPC on default uri not detected, starting bundled CKB node.
[2023-06-15 15:33:53.349] [info]  CKB:	Initializing node...
[2023-06-15 15:33:54.933] [info]  CKB:	starting node...
[2023-06-15 15:33:55.680] [info]  CKB:	process closed
[2023-06-15 15:34:25.378] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:34:25.503] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:34:25.612] [info]  Monitor: is restarting ckb process
[2023-06-15 15:34:25.612] [info]  CKB:	Initializing node...
[2023-06-15 15:34:25.737] [info]  CKB:	starting node...
[2023-06-15 15:34:25.753] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:34:25.846] [info]  CKB:	process closed
[2023-06-15 15:34:55.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:34:55.493] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:34:55.603] [info]  Monitor: is restarting ckb process
[2023-06-15 15:34:55.603] [info]  CKB:	Initializing node...
[2023-06-15 15:34:56.102] [info]  CKB:	starting node...
[2023-06-15 15:34:56.118] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:34:56.181] [info]  CKB:	process closed
[2023-06-15 15:35:25.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:35:25.509] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:35:25.618] [info]  Monitor: is restarting ckb process
[2023-06-15 15:35:25.618] [info]  CKB:	Initializing node...
[2023-06-15 15:35:25.743] [info]  CKB:	starting node...
[2023-06-15 15:35:25.759] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:35:25.837] [info]  CKB:	process closed
[2023-06-15 15:35:55.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:35:55.493] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:35:55.602] [info]  Monitor: is restarting ckb process
[2023-06-15 15:35:55.602] [info]  CKB:	Initializing node...
[2023-06-15 15:35:55.696] [info]  CKB:	starting node...
[2023-06-15 15:35:55.727] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:35:55.806] [info]  CKB:	process closed
[2023-06-15 15:36:25.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:36:25.509] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:36:25.618] [info]  Monitor: is restarting ckb process
[2023-06-15 15:36:25.618] [info]  CKB:	Initializing node...
[2023-06-15 15:36:25.743] [info]  CKB:	starting node...
[2023-06-15 15:36:25.759] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:36:25.837] [info]  CKB:	process closed
[2023-06-15 15:36:55.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:36:55.509] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:36:55.634] [info]  Monitor: is restarting ckb process
[2023-06-15 15:36:55.634] [info]  CKB:	Initializing node...
[2023-06-15 15:36:56.102] [info]  CKB:	starting node...
[2023-06-15 15:36:56.134] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:36:56.274] [info]  CKB:	process closed
[2023-06-15 15:37:25.384] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:37:25.509] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:37:25.618] [info]  Monitor: is restarting ckb process
[2023-06-15 15:37:25.618] [info]  CKB:	Initializing node...
[2023-06-15 15:37:26.009] [info]  CKB:	starting node...
[2023-06-15 15:37:26.040] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:37:26.134] [info]  CKB:	process closed
[2023-06-15 15:37:55.385] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:37:55.510] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:37:55.619] [info]  Monitor: is restarting ckb process
[2023-06-15 15:37:55.619] [info]  CKB:	Initializing node...
[2023-06-15 15:37:55.978] [info]  CKB:	starting node...
[2023-06-15 15:37:55.994] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:37:56.072] [info]  CKB:	process closed
[2023-06-15 15:38:13.716] [info]  Find devices:	 [ [ null ] ]
[2023-06-15 15:38:25.397] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:38:25.522] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:38:25.631] [info]  Monitor: is restarting ckb process
[2023-06-15 15:38:25.631] [info]  CKB:	Initializing node...
[2023-06-15 15:38:25.897] [info]  CKB:	starting node...
[2023-06-15 15:38:25.912] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:38:25.991] [info]  CKB:	process closed
[2023-06-15 15:38:55.399] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:38:55.508] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:38:55.617] [info]  Monitor: is restarting ckb process
[2023-06-15 15:38:55.617] [info]  CKB:	Initializing node...
[2023-06-15 15:38:55.727] [info]  CKB:	starting node...
[2023-06-15 15:38:55.742] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:38:55.836] [info]  CKB:	process closed
[2023-06-15 15:38:56.852] [info]  Find devices:	 [
  [
    {
      isBluetooth: false,
      descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#7&7c7c91f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
      vendorId: 11415,
      manufacturer: 'Ledger',
      product: 'Nano X',
      addressIndex: 0,
      addressType: 0
    }
  ]
]
[2023-06-15 15:38:56.852] [info]  Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#7&7c7c91f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2023-06-15 15:38:56.883] [warn]  API Controller:	channel handling error: TransportStatusError: Ledger device: CLA_NOT_SUPPORTED (0x6e00) Error
    at new TransportStatusError (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\@ledgerhq\errors\lib\index.js:264:18)
    at TransportNodeHid.<anonymous> (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:127:39)
    at step (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:33:23)
    at Object.next (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:14:53)
    at fulfilled (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:5:58)
[2023-06-15 15:39:25.407] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:39:25.514] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:39:25.622] [info]  Monitor: is restarting ckb process
[2023-06-15 15:39:25.628] [info]  CKB:	Initializing node...
[2023-06-15 15:39:25.776] [info]  CKB:	starting node...
[2023-06-15 15:39:25.803] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:39:25.907] [info]  CKB:	process closed
[2023-06-15 15:39:30.028] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:30.033] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:30.040] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:30.069] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:30.074] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:30.079] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:32:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:31:23)
    at WalletsController.generateTx (C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\wallets.js:337:14)
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:264:92
    at C:\Users\PJ\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
[2023-06-15 15:39:55.408] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:39:55.515] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:39:55.626] [info]  Monitor: is restarting ckb process
[2023-06-15 15:39:55.633] [info]  CKB:	Initializing node...
[2023-06-15 15:39:55.745] [info]  CKB:	starting node...
[2023-06-15 15:39:55.765] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:39:55.842] [info]  CKB:	process closed
[2023-06-15 15:40:25.403] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:40:25.507] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:40:25.610] [info]  Monitor: is restarting ckb process
[2023-06-15 15:40:25.613] [info]  CKB:	Initializing node...
[2023-06-15 15:40:25.712] [info]  CKB:	starting node...
[2023-06-15 15:40:25.733] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:40:25.814] [info]  CKB:	process closed
[2023-06-15 15:40:55.405] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:40:55.510] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:40:55.635] [info]  Monitor: is restarting ckb process
[2023-06-15 15:40:55.639] [info]  CKB:	Initializing node...
[2023-06-15 15:40:55.784] [info]  CKB:	starting node...
[2023-06-15 15:40:55.804] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:40:55.883] [info]  CKB:	process closed
[2023-06-15 15:41:05.531] [info]  Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#7&7c7c91f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2023-06-15 15:41:19.990] [info]  Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#7&7c7c91f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2023-06-15 15:41:25.409] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:41:25.513] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:41:25.617] [info]  Monitor: is restarting ckb process
[2023-06-15 15:41:25.621] [info]  CKB:	Initializing node...
[2023-06-15 15:41:26.061] [info]  CKB:	starting node...
[2023-06-15 15:41:26.087] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:41:26.186] [info]  CKB:	process closed
[2023-06-15 15:41:55.413] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:41:55.519] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:41:55.623] [info]  Monitor: is restarting ckb process
[2023-06-15 15:41:55.627] [info]  CKB:	Initializing node...
[2023-06-15 15:41:56.177] [info]  CKB:	starting node...
[2023-06-15 15:41:56.197] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:41:56.292] [info]  CKB:	process closed
[2023-06-15 15:42:25.412] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:42:25.520] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:42:25.627] [info]  Monitor: is restarting ckb process
[2023-06-15 15:42:25.634] [info]  CKB:	Initializing node...
[2023-06-15 15:42:25.992] [info]  CKB:	starting node...
[2023-06-15 15:42:26.012] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:42:26.113] [info]  CKB:	process closed
[2023-06-15 15:42:55.079] [info]  Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#7&7c7c91f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2023-06-15 15:42:55.413] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:42:55.520] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:42:55.629] [info]  Monitor: is restarting ckb process
[2023-06-15 15:42:55.636] [info]  CKB:	Initializing node...
[2023-06-15 15:42:56.005] [info]  CKB:	starting node...
[2023-06-15 15:42:56.028] [info]  Monitor: Restarting ckb process success
[2023-06-15 15:42:56.127] [info]  CKB:	process closed
[2023-06-15 15:43:25.413] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-06-15 15:43:25.521] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-06-15 15:43:25.628] [info]  Monitor: is restarting ckb process
```

### status.log

```shell
-
```

**Comment by yanguoyu** [comment]
Hi, @Arkaier 
I believe that your ckb node process doesn't start success because your bundled-ckb.log is empty.
Could you try to start ckb node manually refer to https://github.com/nervosnetwork/neuron/issues/2701?
