### ISSUE TITLE
[Synchronization] Sync complete but after restart , stuck on connecting

### ISSUE THREAD

**Issue by Kivv88** [nervosnetwork/neuron#2784]
### Detail of the issue

On Windows 11 , i installed neuron and created my wallet.
The app start sync and after a couple of hours, finished (100%). Then when i close the app and reopen it , the app is stuck on "Connecting".
No network issue , 
same effect  
- after restarting the computer
- when lanching with  admin privilleges 

Any idea ?

### bundled-ckb.log

```shell
2023-07-21 14:20:56.827 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-07-21 14:20:56.827 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-07-21 14:20:57.291 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-07-21 14:20:57.292 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-07-21 14:20:57.292 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
2023-07-21 14:21:26.854 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-07-21 14:21:26.854 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-07-21 14:21:27.319 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-07-21 14:21:27.320 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-07-21 14:21:27.320 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
2023-07-24 16:13:17.787 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-07-24 16:13:17.789 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-07-24 16:13:18.437 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-07-24 16:13:18.439 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-07-24 16:13:18.441 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
```

### main.log

```shell
[2023-07-19 09:26:50.583] [info]  App:	Neuron is starting
[2023-07-19 09:26:50.614] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-07-19 09:26:50.719] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-07-19 09:26:50.830] [error] Network:	fail to connect to the network. Is CKB node running?
[2023-07-19 09:26:51.144] [info]  Network:	switched to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2023-07-19 09:26:51.229] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2023-07-19 09:26:51.335] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
[2023-07-19 09:26:51.446] [info]  CKB:	external RPC on default uri not detected, starting bundled CKB node.
[2023-07-19 09:26:51.535] [info]  CKB:	Initializing node...
[2023-07-19 09:26:52.003] [error] CKB:	init fail: WARN: mining feature is disabled because of lacking the block assembler config options

[2023-07-19 09:26:52.004] [info]  CKB:	init result: Initialized CKB directory in C:\xxx\AppData\Roaming\Neuron\chains\mainnet
create ckb.toml

[2023-07-19 09:26:52.006] [info]  CKB:	init result: create ckb-miner.toml

[2023-07-19 09:26:52.008] [info]  CKB:	init result: create default.db-options

[2023-07-19 09:26:52.068] [info]  CKB:	init result: Genesis Hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5

[2023-07-19 09:26:52.071] [info]  CKB:	starting node...
[2023-07-19 09:26:53.006] [info]  Network:	reconnected to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2023-07-19 09:26:56.008] [info]  Sync:	start
[2023-07-19 09:26:57.312] [info]  Queue:	start
[2023-07-19 09:26:57.335] [info]  Database:	saved synced block #0
[2023-07-19 09:27:02.341] [info]  Database:	saved synced block #0
[2023-07-19 09:27:07.352] [info]  Database:	saved synced block #0
[2023-07-19 09:27:12.358] [info]  Database:	saved synced block #0
...
...
[2023-07-19 21:17:42.947] [info]  Database:	saved synced block #10493559
[2023-07-19 21:18:40.617] [info]  Database:	saved synced block #10493570
[2023-07-19 21:19:30.211] [warn]  API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at TransactionGenerator.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:950:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\services\transaction-sender.js:192:24)
    at async DaoController.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\controllers\dao.js:37:20)
    at async F:\xxx\Neuron\resources\app.asar\dist\controllers\api.js:556:33
    at async node:electron/js2c/browser_init:2:97945
[2023-07-19 21:19:30.215] [warn]  API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at TransactionGenerator.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:950:15)
    at async TransactionSender.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\services\transaction-sender.js:192:24)
    at async DaoController.generateDepositAllTx (F:\xxx\Neuron\resources\app.asar\dist\controllers\dao.js:37:20)
    at async F:\xxx\Neuron\resources\app.asar\dist\controllers\api.js:556:33
    at async node:electron/js2c/browser_init:2:97945
```

### status.log

```shell
{"neuron":{"version":"0.110.2","blockNumber":"10493570"},"ckb":{"url":"http://127.0.0.1:8114","version":"","blockNumber":"","peers":[]},"client":{"platform":"win32","arch":"x64","release":"10.0.22621","vcredist":true}}
```

**Comment by yanguoyu** [comment]
Hi, @Kivv88 
It's a known issue https://github.com/nervosnetwork/neuron/issues/2699. I believe https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 can help you.
We will fix it in the next version by updating the ckb version.
