### ISSUE TITLE
[Synchronization] doesn't seems to start syncing

### ISSUE THREAD

**Issue by itsfranzsis** [nervosnetwork/neuron#2940]
### Detail of the issue

Syncing status stuck at "connecting" for very long time. 

### bundled-ckb.log

```shell
File not found
```

### main.log

```shell
[2023-11-15T12:54:42.240Z] [info]  App:	Neuron is starting
[2023-11-15T12:54:43.845Z] [info]  Network:	switched to: {
  id: 'light_client',
  name: 'Light Client',
  remote: 'http://127.0.0.1:9000',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 2,
  chain: 'light_client_mainnet',
  readonly: true
} false
[2023-11-15T12:54:45.944Z] [info]  CKB:	external RPC on default uri detected, skip starting bundled CKB node.
[2023-11-15T12:54:46.686Z] [info]  Network:	reconnected to: {
  id: 'light_client',
  name: 'Light Client',
  remote: 'http://127.0.0.1:9000',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 2,
  chain: 'light_client_mainnet',
  readonly: true
} false
[2023-11-15T12:54:50.082Z] [info]  Checking for update
[2023-11-15T12:54:54.267Z] [info]  Update for version 0.111.1 is not available (latest version: 0.111.1, downgrade is disallowed).
[2023-11-15T12:57:06.846Z] [info]  CKB:	ignore running external node, and start node with another port
[2023-11-15T12:57:06.865Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T12:57:06.948Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T12:57:11.735Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T12:57:11.759Z] [info]  CKB Light Runner:	process closed
[2023-11-15T12:57:12.619Z] [info]  Network:	switched to: {
  id: '21d3c4f6-ec84-49e4-8946-efa31fd9f54a',
  name: 'CKB',
  remote: 'http://127.0.0.1:8114',
  type: 1,
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  chain: 'ckb',
  readonly: false
} true
[2023-11-15T12:57:12.818Z] [info]  CKB:	start verify external ckb node
[2023-11-15T12:57:13.842Z] [info]  Network:	reconnected to: {
  id: '21d3c4f6-ec84-49e4-8946-efa31fd9f54a',
  name: 'CKB',
  remote: 'http://127.0.0.1:8114',
  type: 1,
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  chain: 'ckb',
  readonly: false
} true
[2023-11-15T12:57:15.758Z] [info]  Sync:	start
[2023-11-15T12:57:19.805Z] [info]  Network:	switched to: {
  id: 'mainnet',
  name: 'Internal Node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb',
  readonly: true
} false
[2023-11-15T12:57:19.850Z] [info]  Network:	reconnected to: {
  id: 'mainnet',
  name: 'Internal Node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb',
  readonly: true
} false
[2023-11-15T12:57:19.859Z] [info]  CKB:	start verify external ckb node
[2023-11-15T12:57:23.891Z] [info]  Queue:	start
[2023-11-15T12:57:24.244Z] [info]  Sync:	drain requests
[2023-11-15T12:57:24.261Z] [info]  CKB:	external RPC on default uri detected, skip starting bundled CKB node.
[2023-11-15T12:57:24.268Z] [debug] Sync:	stopping
[2023-11-15T12:57:24.270Z] [debug] Sync:	stopped
[2023-11-15T12:57:27.383Z] [info]  Sync:	start
[2023-11-15T12:57:34.707Z] [info]  Queue:	start
[2023-11-15T12:57:34.831Z] [info]  Sync:	drain requests
[2023-11-15T12:57:34.847Z] [debug] Sync:	stopping
[2023-11-15T12:57:34.848Z] [debug] Sync:	stopped
[2023-11-15T13:05:26.802Z] [info]  CKB:	ignore running external node, and start node with another port
[2023-11-15T13:05:26.839Z] [info]  CKB:	Initializing node...
[2023-11-15T13:05:26.840Z] [info]  CKB:	init: config file detected, skip ckb init.
[2023-11-15T13:05:26.882Z] [info]  CKB:	ckb full node will with rpc port 8116, listen port 8117, with options [
  'run',
  '-C',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/mainnet',
  '--indexer',
  '--assume-valid-target',
  '0x79cecdd6f41361e2474290224751284312a018528d1d92f4e18dd6d542feddfe'
]
[2023-11-15T13:05:28.866Z] [info]  Network:	switched to: {
  id: 'light_client',
  name: 'Light Client',
  remote: 'http://127.0.0.1:9000',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 2,
  chain: 'light_client_mainnet',
  readonly: true
} false
[2023-11-15T13:05:28.871Z] [info]  CKB:	killing node
[2023-11-15T13:05:28.887Z] [info]  CKB:	process closed
[2023-11-15T13:05:28.898Z] [info]  CKB:	external RPC on default uri detected, skip starting bundled CKB node.
[2023-11-15T13:05:30.643Z] [info]  Network:	reconnected to: {
  id: 'light_client',
  name: 'Light Client',
  remote: 'http://127.0.0.1:9000',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 2,
  chain: 'light_client_mainnet',
  readonly: true
} false
[2023-11-15T13:05:38.806Z] [info]  CKB:	ignore running external node, and start node with another port
[2023-11-15T13:05:38.809Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:05:38.815Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:05:39.738Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:05:39.754Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:06:08.922Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:06:09.033Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:06:09.138Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:06:09.139Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:06:09.142Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:06:09.164Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:06:10.249Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:06:10.271Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:06:38.855Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:06:38.986Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:06:39.091Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:06:39.095Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:06:39.139Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:06:39.155Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:06:40.236Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:06:40.241Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:07:08.853Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:07:08.972Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:07:09.080Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:07:09.082Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:07:09.089Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:07:09.105Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:07:09.945Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:07:09.948Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:07:38.855Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:07:38.971Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:07:39.075Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:07:39.077Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:07:39.081Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:07:39.096Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:07:40.069Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:07:40.074Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:07:57.855Z] [info]  Sync:	start
[2023-11-15T13:08:04.423Z] [info]  Queue:	start
[2023-11-15T13:08:04.620Z] [info]  LightConnector:	connect ...:
[2023-11-15T13:08:08.855Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:08:08.958Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:08:09.064Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:08:09.065Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:08:09.067Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:08:09.076Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:08:10.103Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:08:10.125Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:08:26.005Z] [info]  Network:	switched to: {
  id: 'mainnet',
  name: 'Internal Node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb',
  readonly: true
} false
[2023-11-15T13:08:26.008Z] [info]  Sync:	drain requests
[2023-11-15T13:08:26.063Z] [debug] Sync:	stopping
[2023-11-15T13:08:26.392Z] [info]  Network:	reconnected to: {
  id: 'mainnet',
  name: 'Internal Node',
  remote: 'http://127.0.0.1:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb',
  readonly: true
} false
[2023-11-15T13:08:27.915Z] [info]  Database:	saved synced block #0
[2023-11-15T13:08:28.006Z] [info]  Database:	saved synced block #0
[2023-11-15T13:08:49.097Z] [info]  CKB:	ignore running external node, and start node with another port
[2023-11-15T13:08:49.099Z] [info]  CKB:	Initializing node...
[2023-11-15T13:08:49.099Z] [info]  CKB:	init: config file detected, skip ckb init.
[2023-11-15T13:08:49.121Z] [info]  CKB:	ckb full node will with rpc port 8116, listen port 8117, with options [
  'run',
  '-C',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/mainnet',
  '--indexer',
  '--assume-valid-target',
  '0x79cecdd6f41361e2474290224751284312a018528d1d92f4e18dd6d542feddfe'
]
[2023-11-15T13:08:50.806Z] [info]  CKB:	process closed
[2023-11-15T13:08:52.671Z] [info]  Network:	reconnected to: {
  id: 'light_client',
  name: 'Light Client',
  remote: 'http://127.0.0.1:9000',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 2,
  chain: 'light_client_mainnet',
  readonly: true
} false
[2023-11-15T13:08:52.682Z] [info]  CKB:	external RPC on default uri detected, skip starting bundled CKB node.
[2023-11-15T13:08:54.203Z] [info]  CKB:	ignore running external node, and start node with another port
[2023-11-15T13:08:54.205Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:08:54.211Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:08:54.668Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:08:54.673Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:09:24.241Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:09:24.364Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:09:24.470Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:09:24.474Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:09:24.481Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:09:24.507Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:09:26.272Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:09:26.277Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:09:54.233Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:09:54.349Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:09:54.455Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:09:54.459Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:09:54.467Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:09:54.489Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:09:57.289Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:09:57.294Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:10:24.241Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 2 ...
[2023-11-15T13:10:24.362Z] [warn]  function call error: Error: connect ECONNREFUSED 127.0.0.1:9001, retry 3 ...
[2023-11-15T13:10:24.465Z] [info]  Monitor: is restarting ckb process
[2023-11-15T13:10:24.466Z] [info]  CKB Light Runner:	config has init, skip init...
[2023-11-15T13:10:24.478Z] [info]  CKB Light Runner:	ckb light node will start with rpc port 9001, with options [
  'run',
  '--config-file',
  '/Users/zephyrx/Library/Application Support/Neuron/chains/light/mainnet/ckb_light.toml'
]
[2023-11-15T13:10:24.502Z] [info]  Monitor: Restarting ckb process success
[2023-11-15T13:10:25.587Z] [error] CKB Light Runner:	run fail: Error: runtime error: failed to start network since P2P(Transport(Io(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

[2023-11-15T13:10:25.593Z] [info]  CKB Light Runner:	process closed
[2023-11-15T13:10:48.688Z] [warn]  function call error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added, retry 2 ...
[2023-11-15T13:10:48.753Z] [error] Sync:ChildProcess: [2023-11-15T13:10:48.688Z] [warn]  function call error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added, retry 2 ...

[2023-11-15T13:10:48.863Z] [warn]  function call error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added, retry 3 ...
[2023-11-15T13:10:48.864Z] [error] Sync:ChildProcess: [2023-11-15T13:10:48.863Z] [warn]  function call error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added, retry 3 ...

[2023-11-15T13:10:49.119Z] [error] retry saving transactions in 2 seconds due to error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added
    at /Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/ckb-rpc.js:142:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CommonUtils.retry (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/common.js:19:16)
    at async LightRPC.getTransaction (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/ckb-rpc.js:139:22)
    at async RpcService.getTransaction (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/services/rpc-service.js:27:24)
    at async /Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/block-sync-renderer/sync/queue.js:109:46
[2023-11-15T13:10:49.135Z] [error] Sync:ChildProcess: [2023-11-15T13:10:49.119Z] [error] retry saving transactions in 2 seconds due to error: Error: transaction 0x7a05990af1ecd25508b9793c0fa3c5e699129440ea103b3b465f687fed4c99bb status: added
    at /Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/ckb-rpc.js:142:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CommonUtils.retry (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/common.js:19:16)
    at async LightRPC.getTransaction (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/utils/ckb-rpc.js:139:22)
    at async RpcService.getTransaction (/Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/services/rpc-service.js:27:24)
    at async /Volumes/Neuron 0.111.1 1/Neuron.app/Contents/Resources/app.asar/dist/block-sync-renderer/sync/queue.js:109:46

[2023-11-15T13:10:49.139Z] [warn]  function call error: Error: transaction 0xde1b1b3b2deda3a7759912e86e3808464edbe42b2ffac27204cdad5cbf7d8491 status: added, retry 2 ...
[2023-11-15T13:10:49.140Z] [error] Sync:ChildProcess: [2023-11-15T13:10:49.139Z] [warn]  function call error: Error: transaction 0xde1b1b3b2deda3a7759912e86e3808464edbe42b2ffac27204cdad5cbf7d8491 status: added, retry 2 ...

[2023-11-15T13:10:49.250Z] [error] Sync:ChildProcess: [2023-11-15T13:10:49.244Z] [warn]  function call error: Error: transaction 0xde1b1b3b2deda3a7759912e86e3808464edbe42b2ffac27204cdad5cbf7d8491 status: added, retry 3 ...
```

### status.log

```shell
{"neuron":{"version":"0.111.1","blockNumber":"0"},"ckb":{"url":"http://127.0.0.1:9001","version":"","blockNumber":"","peers":[]},"client":{"platform":"darwin","arch":"x64","release":"22.3.0","vcredist":true}}
```

**Comment by Keith-CY** [comment]
This case is very similar to https://talk.nervos.org/t/neuron-stuck-syncing-at-block-5-188-000/7526 we may check them together @yanguoyu

**Comment by Keith-CY** [comment]
I've found several cases caused by the same miner address and opened a specific issue for it at https://github.com/nervosnetwork/neuron/issues/2941

**Comment by itsfranzsis** [comment]
> I've found several cases caused by the same miner address and opened a specific issue for it at https://github.com/nervosnetwork/neuron/issues/2941

When will this issue be fixed?
