### ISSUE TITLE
Cannot Withdraw or send CKB Error Resolve Failed

### ISSUE THREAD

**Issue by jacobtwitch** [nervosnetwork/neuron#3033]
### Topic Type

Cannot Send Transaction

### Detail of the issue

When I try to send CKB to any of my external wallets from Neuron it says TransactionFailedToResolve: Resolve failed Unknown out point.

Both wallets are on the Nervos Network. Any suggestions?  Node is fully synchronized and I downloaded this application last November for this computer.  I ran the update last night so I am on version 0.112.0

The wallet I used to use on a different computer had issues synchronizing for months on end.  I kept clearing cache but after an update last summer I can't get it to sync at all.  That was the computer I used to manage all of my wallets and transactions.  I hope I don't have to find a third computer to put this on to wait another 5 days to sync.

### main.log

```shell
[2024-02-04T17:35:17.040Z] [info]  Sync:	start
[2024-02-04T17:35:19.350Z] [info]  Queue:	start
[2024-02-04T17:35:20.556Z] [info]  Database:	saved synced block #12130267
[2024-02-04T17:37:35.597Z] [info]  Database:	saved synced block #12130360
[2024-02-04T17:39:14.357Z] [info]  Database:	saved synced block #12130370
[2024-02-04T17:42:40.835Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.838Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.840Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.850Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.852Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.854Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.860Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.862Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:40.864Z] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:31:43
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:30:23)
    at WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:341:14)
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:288:92
    at C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:39
    at node:electron/js2c/browser_init:2:98044
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81557)
    at EventEmitter.emit (node:events:513:28)
[2024-02-04T17:42:43.556Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:43.558Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:43.645Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.712Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.801Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.803Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.907Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.995Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:45.996Z] [warn]  API Controller:	channel handling error: Error: The minimal transfer balance is 61 CKBytes. Error: The minimal transfer balance is 61 CKBytes.
    at C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:829:19
    at Array.map (<anonymous>)
    at TransactionGenerator.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:816:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:74:28)
    at async WalletsController.generateTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:342:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:42:54.141Z] [info]  Database:	saved synced block #12130380
[2024-02-04T17:43:00.605Z] [warn]  API Controller:	channel handling error: Error: {"code":-301,"message":"TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x5dc49bc6ac036a62fc4c4e5949fa5fa51aca14ef7f52a0740247310d9e704b5751040000))","data":"Resolve(Unknown(OutPoint(0x5dc49bc6ac036a62fc4c4e5949fa5fa51aca14ef7f52a0740247310d9e704b5751040000)))"} Error: {"code":-301,"message":"TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x5dc49bc6ac036a62fc4c4e5949fa5fa51aca14ef7f52a0740247310d9e704b5751040000))","data":"Resolve(Unknown(OutPoint(0x5dc49bc6ac036a62fc4c4e5949fa5fa51aca14ef7f52a0740247310d9e704b5751040000)))"}
    at C:\Program Files\Neuron\resources\app.asar\node_modules\@ckb-lumos\rpc\lib\method.js:73:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionSender.broadcastTx (C:\Program Files\Neuron\resources\app.asar\dist\services\transaction-sender.js:298:9)
    at async WalletsController.sendTx (C:\Program Files\Neuron\resources\app.asar\dist\controllers\wallets.js:325:20)
    at async C:\Program Files\Neuron\resources\app.asar\dist\controllers\api.js:574:33
    at async node:electron/js2c/browser_init:2:98028
[2024-02-04T17:44:49.428Z] [info]  Database:	saved synced block #12130390
[2024-02-04T17:46:44.592Z] [info]  Database:	saved synced block #12130400
[2024-02-04T17:48:10.803Z] [info]  Database:	saved synced block #12130410
[2024-02-04T17:49:37.096Z] [info]  Database:	saved synced block #12130420
```

**Comment by yanguoyu** [comment]
Hi, @jacobtwitch 
Usually `Resolve failed Unknown out point.` means the cell has been spent. This could be caused by the Neuron not syncing the transaction that spends that cell or missing that transaction for an unknown reason.

Could you try to clear the cache with the default option? Click the settings, and scroll to the end. The `clear cache` button disappears. If after clearing the cache, it does not show your balance. Could you upload the debug information for us to find out the reason?

![image](https://github.com/nervosnetwork/neuron/assets/12881040/d91d079f-80ab-40b3-8f5f-bde7fc08f601)
![image](https://github.com/nervosnetwork/neuron/assets/12881040/ed142751-c0eb-4ee2-91d6-565e7ba3b4bf)
